const Routes = {
  SPLASH: 'SPLASH',
  LOGIN: 'LOGIN',
  HOME: 'HOME',
  SETTINGS: 'SETTINGS',
  ABOUT_APP: 'ABOUT_APP',
  TERMS_AND_CONDITIONS: 'TERMS_AND_CONDITIONS',
  PRIVACY_POLICY: 'PRIVACY_POLICY',
};

export default Routes;
